# Generated by Django 2.2.13 on 2020-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200916_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='fileDownload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
