# Generated by Django 2.2.13 on 2020-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_filedownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='fileDownload',
            field=models.FileField(blank=True, null=True, upload_to='code/'),
        ),
    ]
